app:
    resource: @AppBundle/Controller/
    type:     annotation
    
HomeServer_homepage:
        resource: "@AppBundle/Resources/config/routing.yml"
        prefix:   /
        
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 